name: "Holonix cache"

on:
  push:
    branches:
      - develop

jobs:
  cache-update:
    strategy:
      fail-fast: false

    runs-on: macos-13
    steps:
      - name: "Build launcher"
        run: |
          nix build -L .#hc-launch
