name: "Holonix cache"

on: push

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, macos-13, ubuntu-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v25
        with:
          install_url: https://releases.nixos.org/nix/nix-2.18.0/install

      - name: Use GitHub cache
        uses: DeterminateSystems/magic-nix-cache-action@main

      - run: nix build -L .#hc-launch

      - run: result/bin/hc-launch --version
